package main

import (
	"fmt"
	"testing"
)

func Test_Uncompress(t *testing.T) {
	fmt.Println(UnCompress("BHCJSBCSCW[100|DASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWF]WQJDWQUINCQQW[99|SDWQJCIQIUWCNQUCNWQIDNWQUIFNSALQP]DQOJOIXZALPPQQAAX\n"))
}
